// <auto-generated />
using System;
using ICSApp.ActivityService.Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ICSApp.ActivityService.Infra.Migrations
{
    [DbContext(typeof(ActivityDbContext))]
    partial class ActivityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ICSApp.ActivityService.Domain.Entities.Activity", b =>
                {
                    b.Property<int>("IdActivity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataHoraInsercao")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DataHoraUltimaAtualizacao")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateClosed")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DateOpen")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(300)")
                        .HasMaxLength(300)
                        .IsUnicode(false);

                    b.Property<int>("IdIncident")
                        .HasColumnType("int");

                    b.Property<int>("IdSection")
                        .HasColumnType("int");

                    b.Property<int>("IdStatus")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioInsercao")
                        .HasColumnType("text");

                    b.Property<string>("UsuarioUltimaAtualizacao")
                        .HasColumnType("text");

                    b.HasKey("IdActivity");

                    b.HasIndex("IdSection");

                    b.HasIndex("IdStatus");

                    b.ToTable("Activity");
                });

            modelBuilder.Entity("ICSApp.ActivityService.Domain.Entities.Section", b =>
                {
                    b.Property<int>("IdSection")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("IdSection");

                    b.ToTable("Section");
                });

            modelBuilder.Entity("ICSApp.ActivityService.Domain.Entities.Status", b =>
                {
                    b.Property<int>("IdStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("IdStatus");

                    b.ToTable("Status");
                });

            modelBuilder.Entity("ICSApp.ActivityService.Domain.Entities.Activity", b =>
                {
                    b.HasOne("ICSApp.ActivityService.Domain.Entities.Section", "Section")
                        .WithMany("Activities")
                        .HasForeignKey("IdSection")
                        .IsRequired();

                    b.HasOne("ICSApp.ActivityService.Domain.Entities.Status", "Status")
                        .WithMany("Activities")
                        .HasForeignKey("IdStatus")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
